import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from 'next/font/google'
import QRCodeStyling from "qr-code-styling";
// const inter = Inter({ subsets: ['latin'] })
import { useState,useRef,useEffect } from 'react';

export default function DirectPayQr({props}) {
  const qrCode = new QRCodeStyling({
    width: 300,
    height: 300,
    image:
      "/img/payken-qr.png",
    dotsOptions: {
      color:"rgb(1 23 4)",
      type: "rounded"
    },
   
    imageOptions: {
      crossOrigin: "anonymous",
      margin:6
    }
  });
  const [url, setUrl] = useState(props);
  const [fileExt, setFileExt] = useState("png");
  const ref = useRef(null);

  useEffect(() => {
    qrCode.append(ref.current);
  }, []);

  useEffect(() => {
    qrCode.update({
      data: url
    });
  }, [url]);

  const onUrlChange = (event) => {
    event.preventDefault();
    setUrl(event.target.value);
  };

  const onExtensionChange = (event) => {
    setFileExt(event.target.value);
  };

  const onDownloadClick = () => {
    qrCode.download({
      extension: fileExt
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <div ref={ref} />
      <div style={{marginTop:'1rem'}} className="App qr-app">
      {/* <div style={styles.inputWrapper}> */}
        <input style={{padding:'8px 10px'}} className='qr-input' value={url} onChange={onUrlChange}  />
        <select style={{padding:'11px 10px',marginLeft:'1rem'}}  className='qr-select' onChange={onExtensionChange} value={fileExt}>
          <option value="png">PNG</option>
          <option value="jpeg">JPEG</option>
          <option value="webp">WEBP</option>
        </select>
        <button className='downloadQR' onClick={onDownloadClick}>Download</button>
      </div>
    {/* </div> */}
    </>
  )
}
